"""add_hashed_password_to_user

Revision ID: add_hashed_password
Revises: bd3da9817b06
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_hashed_password'
down_revision = 'bd3da9817b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # Use batch_alter_table for SQLite compatibility when altering columns
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('clerk_id',
               existing_type=sa.String(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert clerk_id nullable change using batch_alter_table for SQLite
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('clerk_id',
               existing_type=sa.String(length=100),
               nullable=False)

    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
