"""add_timestamp_mixin_to_payment

Revision ID: dbd8c5c37193
Revises: add_hashed_password
Create Date: 2025-11-18 10:09:47.367556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd8c5c37193'
down_revision: Union[str, Sequence[str], None] = 'add_hashed_password'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Thêm cột updated_at với giá trị mặc định là created_at (hoặc now) cho các record cũ
    from datetime import datetime, timezone
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # Cập nhật giá trị cho các record cũ: updated_at = created_at
    op.execute("UPDATE payments SET updated_at = created_at WHERE updated_at IS NULL")
    # Sau đó set NOT NULL
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'updated_at')
    # ### end Alembic commands ###
